#!/bin/bash -x
# ./run "Custom hex color" "#ffcc00"

folder=${folder:-none}
rm -rf /home/node/tts/$folder/media

colors=(orange)
#colors=(red blue green purple cyan magenta yellow orange)
COLOR_DEFAULT="${colors[RANDOM % ${#colors[@]}]}"
cp -a text_scene.py /home/node/tts/$folder/

  #-v "$(pwd)":/manim \
docker run --rm \
  -v "/home/node/tts/$folder":/manim \
  -u "$(id -u)":"$(id -g)" \
  -e TEXT="${1:-Hello 1from Manim!}" \
  -e COLOR="$COLOR_DEFAULT" \
  -e FONT_SIZE="${2:-50}" \
  -e SHIFT_X="${3:-0.0}" \
  -e SHIFT_Y="${4:-0.0}" \
  manimcommunity/manim \
   manim -ql -t -o text_alpha.webm ./text_scene.py TextScene
#  manim -ql ./text_scene.py TextScene


  ffmpeg1(){

  #cd media/videos/text_scene/480p15
  cd /home/node/tts/$folder
 cd media/videos/text_scene/480p15
  ffmpeg -i /home/node/tts/background/back-45.mp4 -i text_alpha.webm.mov \
  -filter_complex "[1:v]scale=1920:-1[fg];[0:v][fg]overlay=0:0:format=auto" \
  -c:v libx264 -pix_fmt yuv420p -c:a copy back-for-before.mp4 -y
  cp -a back-for-before.mp4 /home/node/tts/$folder/

  }
  ffmpeg1

  if [ -e /home/node/tts/debug/back-for-before.mp4 ]; then
    cp -a /home/node/tts/$folder/back-for-before.mp4 /mnt/c/ffmpeg/c/
    sleep 3
  fi