#!/usr/bin/env bash
set -x 
folder=${folder:-/home/baum/a}
back=${back:-/home/baum/a}
tool=${tool:-/home/baum/src/python/movement}
seed_num=$((3 +RANDOM % 800))
output_file=${output_file:-output.mp4}
in_file=${in_file:-back-45.mp4}
echo "seed_num: $seed_num"
echo "output_file: $output_file"
echo "in_file: $in_file"
echo "back: $back"
echo "folder: $folder"
echo "tool: $tool"

start_num=${start_num:-none}
if [ "$start_num" = "none" ]; then
  start_num=$((3 +RANDOM % 5))
fi


echo "start_num: $start_num"
duration_num=$((1 + RANDOM % 1))
echo "duration_num: $duration_num"
speed_num=$((333 + (RANDOM % 121)))   # 180..300
echo "speed_num: $speed_num"

docker run --rm \
  -v ${back}:/in:ro \
  -v ${tool}:/workspace/tool:ro \
  -v ${folder}:/out \
  cursor-move:latest \
  /workspace/tool/main.py \
    --video /in/${in_file} \
    --cursor /in/cursor.png \
    --out /out/${output_file} \
    --duration $duration_num \
    --start $start_num \
    --speed $speed_num \
    --segment 1.5 \
    --scale 0.24 \
    --seed $seed_num

cp -a /home/baum/a/output.mp4 /mnt/c/ffmpeg/