#!/usr/bin/env bash
set -x 


#seed_num=$(( (RANDOM << 16) | RANDOM ))
seed_num=$((3 +RANDOM % 800))
echo "seed_num: $seed_num"

start_num=$((3 +RANDOM % 5))
echo "start_num: $start_num"
duration_num=$((2 + RANDOM % 3))
echo "duration_num: $duration_num"
speed_num=$((180 + (RANDOM % 121)))   # 180..300
echo "speed_num: $speed_num"

docker run -ti --rm \
  -v /home/baum/a:/in:ro \
  -v /home/baum/src/python/movement:/workspace/tool:ro \
  -v /home/baum/a:/out \
  cursor-move:latest \
  /workspace/tool/main.py \
    --video /in/back-45.mp4 \
    --cursor /in/cursor.png \
    --out /out/output.mp4 \
    --duration $duration_num \
    --start $start_num \
    --speed $speed_num \
    --segment 1.5 \
    --scale 0.24 \
    --seed $seed_num

cp /home/baum/a/output.mp4 /mnt/c/ffmpeg