server {
    listen 80;
    server_name paperclip.devopsite.top;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name paperclip.devopsite.top;     
    ssl_certificate /home/baum/.acme.sh/devopsite.top_ecv/fullchain.cer;
    ssl_certificate_key /home/baum/.acme.sh/devopsite.top_ecv/devopsite.top.key;
    ssl_trusted_certificate /home/baum/.acme.sh/devopsite.top_ecv/ca.cer;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    client_max_body_size 10M;

    location /uploads {
        upload_pass @rails;
        upload_store /var/www/my_app/tmp/uploads;
        upload_store_access user:rw;
        upload_set_form_field "${upload_field_name}_path" $upload_tmp_path;
        upload_set_form_field "${upload_field_name}_original_name" $upload_original_name;
        upload_set_form_field "${upload_field_name}_content_type" $upload_content_type;
        upload_cleanup 400 404 499 500-599;
    }

    location @rails {
        proxy_pass http://192.168.0.179:3007;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

location /{
    proxy_pass http://192.168.0.179:3007;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_cache_bypass $http_upgrade;
    }
}

