#!/bin/bash -x 





base_folder="${base_folder:-/mnt/c/share/1}"
p1="Baum la morning todat yesterday lovely"
p2="lala mumu tomer baum orit arielle yair aviv baum hani margalit Baum la morning todat yesterday lovely"
p3="kuku lala mumu tomer baum orit arielle yair aviv baum hani margalit Baum la morning todat yesterday lovely"
hook="aaa 4 Prompts to help you solve X Problem"




bash reels-ver2.sh render_kind 2 \
      --png page1-5.png \
      --out slide1.mp4 \
      --text "\"${hook}\" " \
      --words 4 \
      --img aa.png \
      --imgw 700 \
      --imgh 700 \
      --yoff -520 \
      --mid-outline 0 \
      --mid-color blue 


bash reels-ver2.sh render_kind 1 \
      --png page2-5.png \
      --out slide2.mp4 \
      --text "Prompt \"${p1}\"" \
      --words 4 \
      --yoff -100 \
      -- \
      --mid-size 70 \
      --mid-outline 0 \
      --mid-color black



# a1 page1-5
# a2 page2-5
# a3 page3-5
# a4 page4-5
# a5 page5-5
# tran5ver2


# bash reels-ver2.sh render_kind 4 \
#   --png page3-5.png \
#   --out slide3.mp4 \
#   --text "Prompt2 'TITLE LINE lala mimi nunu' " \
#   --text2 "Prompt3: 'lili kkkk subtitle line here tomer baum baum2' " \
#   --words 4 \
#   --yoff -160 \
#   --yoff2 340 \
#   --size2 60 -- \
#   --mid-size 90 \
#   --mid2-size 90 \
#   --mid-color black \
#   --mid-outline 0 \
#   --mid-outline-color black \
#   --mid2-font-color black \
#   --mid2-outline 0

bash reels-ver2.sh render_kind 1 \
      --png page3-5.png \
      --out slide3.mp4 \
      --text "Prompt \"${p2}\"" \
      --words 4 \
      --yoff -100 \
      -- \
      --mid-size 70 \
      --mid-outline 0 \
      --mid-color black

bash reels-ver2.sh render_kind 1 \
  --png page4-5.png \
  --out slide4.mp4 \
  --text "Prompt \"${p3}\" " \
  --words 4 \
  --yoff -100 \
  -- \
  --mid-size 70 \
  --mid-color black \
  --mid-outline 0 \
  --mid-outline-color black



bash reels-ver2.sh render_kind 3 \
       --png page5-5.png \
       --out slide5.mp4 \
       --img cta.png \
       --imgw 800 \
       --imgh 800 \
       --mid-img-y-mm-offset -70




   bash reels-ver2.sh merge_master \
  --slide1 "${base_folder}/slide1.mp4" \
  --slide2 "${base_folder}/slide2.mp4" \
  --slide3 "${base_folder}/slide3.mp4" \
  --slide4 "${base_folder}/slide4.mp4" \
  --slide5 "${base_folder}/slide5.mp4" \
  --audio "${base_folder}/3.mp3" \
  --out "${base_folder}/master5.mp4" \
  --hold 2.4 \
  --trans 1.2 \
  --mid-x 0 --mid-y 300 --mid-w 1080 --mid-h 1220













exit 0
only_mid_text(){
bash reels-ver2.sh render_slide1 \
  --png  /mnt/c/share/1/$1 \
  --out  /mnt/c/share/1/$2 \
  --font  /mnt/c/share/1/KGLoveMolly.ttf \
  --mid-text "$3" --words-per-line $4 \
  --mid-y-offset -$5 \
  --top-text "TOP TITLE HERE" \
  --bot-text "BOTTOM CTA" \
  --mid-color blue \
  --mid-outline 0
}


  #TOP_H=220 MID_Y=220 MID_H=1480 BOT_Y=1700 BOT_H=220 \
#bash reels-ver2.sh render_slide1 --png file1.png --out out/slide1.mp4 --font ./path/to/font.ttf


if_need_pic(){

    render_kind 2 \
      --png page1.png \
      --out slide1.mp4 \
      --text "pov need to think of a prompt" \
      --words 4 \
      --img aa.png \
      --imgw 900 \
      --imgh 900
}

pic_final(){

  render_kind 3 \
    --png page4.png \
    --out slide4.mp4 \
    --img aa.png \
    --imgw 800 \
    --imgh 800 \
  --mid-img-y-mm-offset -70
}

tran4(){
   bash reels-ver2.sh merge_master \
  --slide1 /mnt/c/share/1/slide1.mp4 \
  --slide2 /mnt/c/share/1/slide2.mp4 \
  --slide3 /mnt/c/share/1/slide3.mp4 \
  --slide4 /mnt/c/share/1/slide4.mp4 \
  --audio /mnt/c/share/1/1.mp3 \
  --out /mnt/c/share/1/master.mp4 \
  --hold 1.7 \
  --trans 0.7 \
  --mid-x 0 --mid-y 300 --mid-w 1080 --mid-h 1120
 
}


# kind 1 text only 
#kind 2 text + pic 
#kind=3  picture only 


a1(){
    render_kind 2 \
      --png $1.png \
      --out slide1.mp4 \
      --text "4 Prompts to help you solve X Problem" \
      --words 4 \
      --img aa.png \
      --imgw 900 \
      --imgh 900 \
      --mid-outline 1 \
      --mid-color red 
}

 
#if_need_pic

#--mid-size 70 or 120 
a2(){
    render_kind 1 \
      --png $1.png \
      --out slide2.mp4 \
      --text "Prompt1: 'Baum la morning todat yesterday lovely'" \
      --mid-size 70 \
      --words 4 \
      --mid-outline 0 \
      --mid-color black 
}

    #   render_kind 1 \
    #   --png page3.png \
    #   --out slide3.mp4 \
    #   --text "Prompt : 'ku ku lala tomer' baum univerecity doda mother father lala Tomer Baum" \
    #   --words 4 \
    #   --mid-outline-color black\
    #   --mid-outline 0 \
    #   --mid-size 70 \
    #   --mid-font-color black

a3(){
render_kind 4 \
  --png $1.png \
  --out slide3.mp4 \
  --text "Prompt2 'TITLE LINE lala mimi nunu' " \
  --text2 "Prompt3: 'lili kkkk subtitle line here tomer baum baum2' " \
  --words 4 \
  --yoff -160 \
  --yoff2 340 \
  --size2 60 -- \
  --mid-size 90 \
  --mid2-size 90 \
  --mid-color black \
  --mid-outline 0 \
  --mid-outline-color black \
  --mid2-font-color black \
  --mid2-outline 0
}




a4(){
render_kind 1 \
  --png $1.png \
  --out slide4.mp4 \
  --text "Prompt4 'TITLE LINE lala mimi nunu kkkkk jjjjj yyyyyy' " \
  --words 4 \
  --mid-size 70 \
  --mid-color black \
  --mid-outline 0 \
  --mid-outline-color black 
}

a41(){

       render_kind 3 \
       --png $1.png \
       --out slide4.mp4 \
       --img aa.png \
       --imgw 800 \
       --imgh 800 \
       --mid-img-y-mm-offset -70
}

a5(){

       render_kind 3 \
       --png $1.png \
       --out slide5.mp4 \
       --img cta.png \
       --imgw 800 \
       --imgh 800 \
       --mid-img-y-mm-offset -70
}
#only_mid_text page2.png slide2.mp4 "Tomer Baum" 4 10

#only_mid_text page3.png slide3.mp4 "kuku kuku" 4 10

#only_mid_text page4.png slide4.mp4 "yair aviv baum ariel orit tomer" 4 280


four_slide(){
a1 page1
a2 page2
a3 page3
a4 page4
tran4
}

#four_slide


tran5(){
   bash reels-ver2.sh merge_master \
  --slide1 /mnt/c/share/1/slide1.mp4 \
  --slide2 /mnt/c/share/1/slide2.mp4 \
  --slide3 /mnt/c/share/1/slide3.mp4 \
  --slide4 /mnt/c/share/1/slide4.mp4 \
  --slide5 /mnt/c/share/1/slide5.mp4 \
  --audio /mnt/c/share/1/2.mp3 \
  --out /mnt/c/share/1/master5.mp4 \
  --hold 1.7 \
  --trans 0.7 \
  --mid-x 0 --mid-y 300 --mid-w 1080 --mid-h 1120
 
}


tran5ver2(){
   bash reels-ver2.sh merge_master \
  --slide1 /mnt/c/share/1/slide1.mp4 \
  --slide2 /mnt/c/share/1/slide2.mp4 \
  --slide3 /mnt/c/share/1/slide3.mp4 \
  --slide4 /mnt/c/share/1/slide4.mp4 \
  --slide5 /mnt/c/share/1/slide5.mp4 \
  --audio /mnt/c/share/1/3.mp3 \
  --out /mnt/c/share/1/master5.mp4 \
  --hold 2.4 \
  --trans 1.2 \
  --mid-x 0 --mid-y 300 --mid-w 1080 --mid-h 1220
 
}



five_slide(){
a1 page1-5
a2 page2-5
a3 page3-5
a4 page4-5
a5 page5-5
tran5ver2
}
five_slide